backend/models/Posts.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "posts".
 *
 * @property int $id
 * @property int $post_by
 * @property int|null $category_id
 * @property string $title
 * @property string $body
 * @property string $image
 * @property string $slug
 * @property int $status
 * @property string $created_at
 *
 * @property User $postBy
 */
class Posts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'posts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['post_by', 'title', 'body', 'image'], 'required'],
            [['post_by', 'category_id', 'status'], 'integer'],
            [['body'], 'string'],
            [['created_at'], 'safe'],
            [['title'], 'string', 'max' => 100],
            [['image'], 'string', 'max' => 200],
            [['slug'], 'string', 'max' => 255],
//            [['post_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['post_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'post_by' => Yii::t('app', 'Post By'),
            'category_id' => Yii::t('app', 'Category ID'),
            'title' => Yii::t('app', 'Title'),
            'body' => Yii::t('app', 'Body'),
            'image' => Yii::t('app', 'Image'),
            'slug' => Yii::t('app', 'Slug'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    /**
     * Gets query for [[PostBy]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPostBy()
    {
        return $this->hasOne(User::className(), ['id' => 'post_by']);
    }
    public function getPostByCat($id){
        $data = Posts::find()->select('id')->where('id',$id)->asArray()->all();
    }
}

backend/models/PostsController.php
<?php

namespace backend\models;

use Yii;
use backend\models\Posts;
use backend\models\PostsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PostsController implements the CRUD actions for Posts model.
 */
class PostsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Posts models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Posts model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Posts model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Posts();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Posts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Posts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Posts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Posts the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/models/Posts.php
<?php

namespace frontend\models;

use Yii;
use common\models\User;
use skeeks\yii2\slug\SlugBehavior;

/**
 * This is the model class for table "posts".
 *
 * @property int $id
 * @property int $post_by
 * @property string $title
 * @property string $body
 * @property string $image
 * @property int $status
 * @property string $slug
 * @property string $created_at
 *
 * @property User $postBy
 */
class Posts extends \yii\db\ActiveRecord
{
    public $captcha;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'posts';
    }

    public function behaviors()
    {
        return [
            'slug' => [
                'class' => 'skeeks\yii2\slug\SlugBehavior',
                'slugAttribute' => 'slug',                      //The attribute to be generated
                'attribute' => 'title',                          //The attribute from which will be generated
                // optional params
                'maxLength' => 64,                              //Maximum length of attribute slug
                'slugifyOptions' => [
                    'trim' => true,
                    'lowercase' => true,
                    'separator' => '-',
                ],
            ],
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ],
        ];
    }

    /**
     * {@inheritdoc}f
     */
    public function rules()
    {
        return [
            [['title', 'image', 'body', 'captcha', 'slug'], 'required'],
            [['body'], 'string'],
            [['id', 'post_by', 'created_at', 'rating'], 'safe'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Category::className(), 'targetAttribute' => ['category_id' => 'id']],
            [['image'], 'string', 'max' => 200],
            [['slug'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => 'jpg,png,gif', 'maxFiles' => 3],
            [['post_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['post_by' => 'id']],
            ['captcha', 'captcha'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'post_by' => Yii::t('app', 'Post By'),
            'rating' => Yii::t('app', 'Rating'),
            'category_id' => Yii::t('app', 'Category ID'),
            'title' => Yii::t('app', 'Title'),
            'body' => Yii::t('app', 'Body'),
            'image' => Yii::t('app', 'Image'),
            'status' => Yii::t('app', 'Status'),
            'slug' => Yii::t('app', 'Slug'),
            'created_at' => Yii::t('app', 'Created At'),
        ];
    }

    /**
     * Gets query for [[PostBy]].
     *
     * @return \yii\db\ActiveQuery
     */

    public function getPostby()
    {
        return $this->hasOne(User::className(), ['id' => 'post_by']);
    }

    public function getCategoryid()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }
}

backend/controllers/PostsController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Posts;
use backend\models\PostsSearch;
use yii\web\Controller;
use yii\base\Model;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;


/**
 * PostsController implements the CRUD actions for Posts model.
 */
class PostsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Posts models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Posts model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Posts model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Posts();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Posts model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Posts model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Posts model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Posts the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
}

frontend/controllers/PostsController.php
<?php

namespace frontend\controllers;

use frontend\controllers\Post;
use frontend\models\Category;
use frontend\models\Posts;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\Controller;
use yii\filters\AccessControl;
use Yii;
use yii\web\UploadedFile;
use yii\web\HttpException;

class PostsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update'],
                'rules' => [
                    [
                        'actions' => ['create', 'update'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    public function actionIndex()
    {
        $user_id = Yii::$app->user->identity->id;
        $model = Posts::find()->where(['post_by' => $user_id])->all();
        return $this->render('index', ['model' => $model]);
    }

    public function actionCategory($id)
    {
        $pages = new Pagination();
        $model = Posts::find()->where(['category_id' => $id])->limit(10)->all();
        return $this->render('category', ['model' => $model, 'pages' => $pages]);
    }

    public function actionCreate()
    {
        $model = new Posts();
        if ($model->load(Yii::$app->request->post())) {
            $model->post_by = Yii::$app->user->identity->getId();
            $images = UploadedFile::getInstances($model, 'image');
            foreach ($images as $image) {
                $image->saveAs('images/upload/' . $image->baseName . '.' . $image->extension);
            }
            $model->image = $image->baseName . '.' . $image->extension;
            if ($model->save(false)) {
                return $this->redirect(['post', 'id' => $model->id]);
            }
        }
        return $this->render('create', ['model' => $model]);
    }

    public function actionUpdate($id)
    {
        $user_id = Yii::$app->user->identity->id;
        $model = Posts::findOne(['id' => $id, 'post_by' => $user_id]);
        if ($model->load(Yii::$app->request->post())) {
            $model->post_by = Yii::$app->user->identity->getId();
            if ($model->save(false)) {
                return $this->redirect(['post', 'id' => $id]);
            }
        }
        return $this->render('update', ['model' => $model]);
    }

    public function actionDelete($id)
    {
        $user_id = Yii::$app->user->identity->id;
        if (Posts::findOne(['id' => $id, 'post_by' => $user_id])) {
            $model = Posts::find()->where(['id' => $id])->one();
            if ($model->delete()) {
                return $this->redirect(['index']);
            }
        }
    }

    public function actionPost($id)
    {
        $post = Posts::findOne(['id' => $id]);
        return $this->render('post', ['post' => $post]);
    }
}

frontend/views/posts/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="posts-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'post_by') ?>

    <?= $form->field($model, 'category_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'body') ?>

    <?php // echo $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'slug') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/posts/category.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use frontend\models\Posts;
use frontend\components\SmallBody;
use yii\widgets\LinkPager;

?>

<div class="container">

    <section class="section-content">
        <div class="container">
            <div class="row ">
                <div class="col-md-1 full-width-content">
                    <?php foreach ($model as $category) { ?>
                        <article class="content-item">
                            <div class="entry-media">
                                <div class="post-title">
                                    <h2>
                                        <a href="<?= Url::toRoute(['/posts/post', 'id' => $category->id]) ?>"><?= $category->title ?></a>
                                    </h2>
                                    <div class="entry-date">
                                        <ul>
                                            <li>
                                                <a href="<?= Url::toRoute(['/category/', 'id' => $category->categoryid->id]) ?>"><?= $category->categoryid->title ?></a>
                                            </li>
                                            <li>
                                                <a href="<?= Url::toRoute(['/user/view/', 'id' => $category->postby->id]) ?>"><?= $category->postby->name ?></a>
                                            </li>
                                            <li><?= $category->created_at ?></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="bubble-line"></div>
                                <div class="post-content full-width">
                                    <img src="/images/upload/<?= $category->image ?>">
                                    <p>
                                        <?= SmallBody::widget(['body' => $category->body]) ?>
                                    </p>
                                </div>
                                <div class="bubble-line"></div>
                                <div class="post-footer">
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <a href="<?= Url::toRoute(['/posts/post', 'id' => $category->id]) ?>"
                                               class="button">Continue reading</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </article>
                    <?php } ?>
                </div>
            </div>
    </section>
</div>

frontend/views/posts/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use yii\helpers\ArrayHelper;
use frontend\models\Category;
use yii\captcha\Captcha;

?>
<div class="container">
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
    <?= $form->field($model, 'title')->textInput() ?>

    <?= $form->field($model, 'category_id')->dropDownList(
        ArrayHelper::map(Category::find()->all(), 'id', 'title'),
        ['prompt' => 'Select Category'])
    ?>

    <?= \yii\redactor\widgets\Redactor::widget([
        'model' => $model,
        'attribute' => 'body'
    ]) ?>
    <?= Yii::t('app', 'Image') ?>
    <?= FileInput::widget([
        'model' => $model,
        'attribute' => 'image',
        'options' => ['multiple' => false,
            'required' => true]
    ]);
    ?>
    <?= $form->field($model, 'captcha')->widget(Captcha::className()) ?>
    <?= $form->field($model, 'status')->dropDownList([1 => 'Active', 0 => 'Inactive']) ?>
    <?= Html::submitButton('Post', ['class' => 'btn btn-primary']) ?>
    <?php ActiveForm::end() ?>
</div>

frontend/views/posts/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="container">
    <h2><?= Yii::t('app', 'Manage your post') ?></h2>
    <a href="<?= Url::to(['create']) ?>" class="btn btn-success pull-right">Create Post</a>
    <table class="table table-striped table-bordered">
        <tr>
            <th>#</th>
            <th><?= Yii::t('app', 'Title') ?></th>
            <th><?= Yii::t('app', 'Posted Date') ?></th>
            <th></th>
        </tr>
        <?php
        $n = 1;
        foreach ($model as $post) {
            ?>
            <tr>
                <td><?= $n ?></td>
                <td><?= $post->title ?></td>
                <td><?= $post->created_at ?></td>
                <td><a href="<?= Url::to(['view', 'id' => $post->id]) ?>"><?= Yii::t('app', 'View') ?></a> |
                    <a href="<?= Url::to(['update', 'id' => $post->id]) ?>"><?= Yii::t('app', 'Update') ?></a> |
                    <a href="<?= Url::to(['delete', 'id' => $post->id]) ?>"><?= Yii::t('app', 'Delete') ?></a>
                </td>
            </tr>
            <?php
            $n++;
        } ?>
    </table>
</div>

frontend/views/posts/post.php
<?php

use frontend\models\Posts;
use yii\helpers\Html;
use yii\helpers\Url;
use yii2mod\comments\widgets\Comment;
use yii\helpers\StringHelper;

$this->title = $post->title;
?>
<?= $this->registerMetaTag([

])
?>
<section class="section-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-8">
                <article class="content-item">
                    <div class="entry-media">
                        <div class="post-title">
                            <h2><a href="javascript:;"><?=$post->title?></a></h2>
                            <div class="entry-date">
                                <ul>
                                    <li><?=$post->created_at?></li>
                                    <li>
                                        <?= \chiliec\vote\widgets\Vote::widget([
                                            'model' => $post,
                                            // optional fields
                                            'showAggregateRating' => false,
                                        ]);?>
                                    </li>
                                </ul>
                            </div>
                                    <a href="/index?r=posts%2Fupdate&id=<?= $post->id ?>"
                                       class="btn btn-primary btn-sm styled">Update</a>
                                    <a href="/index?r=posts%2Fdelete&id=<?= $post->id ?>"
                                       class="btn btn-success btn-sm styled"">Delete</a>
                        </div>
                        <div class="bubble-line"></div>
                        <div class="post-content">
                            <img src="/images/upload/<?=$post->image?>">
                            <?=$post->body?>
                        </div>
                        <div class="bubble-line"></div>
                        <div class="post-footer">
                            <div class="row">
                                <div class="col-sm-7 text-right">
                                    <div class="content-social">
                                        <a href="https://www.facebook.com/sharer.php?u=<?=Yii::$app->request->url?>"><i
                                                class="fa fa-facebook"></i><span>Facebook</span></a>
                                        <a href="https://twitter.com/intent/tweet?text=<?=Yii::$app->request->url?>"><i class="fa fa-twitter"></i><span>Twitter</span></a>
                                        <a href="https://www.linkedin.com/shareArticle?mini=true&url=<?=Yii::$app->request->url?>"><i
                                                class="fa fa-linkedin"></i><span>LinkedIn</span></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>

                <article class="content-item">
                    <div class="entry-media">
                        <div class="post-title">
                            <h2>Leave a reply</h2>
                        </div>
                        <div class="bubble-line"></div>
                        <div class="post-content comment">
                            <?php
                            $model = Posts::find()->where(['title'=>$post->title])->one();
                            echo Comment::widget([
                                'model' => $model,
                                'dataProviderConfig' => [
                                    'pagination' => [
                                        'pageSize' => 10
                                    ],
                                ]
                            ]); ?>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </div>
</section>

frontend/views/posts/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use dosamigos\tinymce\TinyMce;
use frontend\models\Category;
use yii\helpers\ArrayHelper;

?>
<div class="container">
    <h3>Update</h3>
    <?php $form = ActiveForm::begin() ?>
    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'category_id')->dropDownList(
        ArrayHelper::map(Category::find()->all(), 'id', 'title'),
        ['prompt' => 'Select Category'])
    ?>
    <?= $form->field($model, 'body')->widget(TinyMce::className(), [
        'options' => ['rows' => 5],
        'language' => 'vi_VN',
        'clientOptions' => [
            'toolbar' => "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent | link image"
        ]
    ]); ?>

    <!--    <? //= $form->field($model, 'image[]')->fileInput(['multiple'=>true,'accept'=>'image/*']); ?>-->
    <?= FileInput::widget([
        'model' => $model,
        'attribute' => 'image',
        'options' => ['multiple' => true]
    ]);
    ?>
    <?= $form->field($model, 'status')->dropDownList([1 => 'Active', 0 => 'Inactive']) ?>
    <?= Html::submitButton('Post', ['class' => 'btn btn-primary']) ?>
    <?php ActiveForm::end() ?>
</div>

frontend/views/posts/vote.php
<?php
?>
<div class="vote-row text-center" id="vote-<?=$modelId?>-<?=$targetId?>" data-placement="top" data-container="body" data-toggle="popover">
    <span  class="glyphicon glyphicon-chevron-up" onclick="vote(<?=$modelId?>, <?=$targetId?>, 'like'); return false;" style="cursor: pointer;"></span><br /><span id="vote-up-<?=$modelId?>-<?=$targetId?>"><?=$likes?></span>
    <div id="vote-response-<?=$modelId?>-<?=$targetId?>">
        <?php if ($showAggregateRating) { ?>
            <?=Yii::t('vote', 'Aggregate rating')?>: <?=$rating?>
        <?php } ?>
    </div>
</div>
<div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <meta itemprop="interactionCount" content="UserLikes:<?=$likes?>"/>
    <meta itemprop="interactionCount" content="UserDislikes:<?=$dislikes?>"/>
    <meta itemprop="ratingValue" content="<?=$rating?>"/>
    <meta itemprop="ratingCount" content="<?=$likes+$dislikes?>"/>
    <meta itemprop="bestRating" content="10"/>
    <meta itemprop="worstRating" content="0"/>
</div>
f